// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package modules

import (
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func InitializeServer() Server {
	repository := NewRepository()
	handler := NewHandler(repository)
	echoEcho := echo.New()
	server := NewServer(handler, echoEcho)
	return server
}
